create table USER_PROFILE (
	USER_ID NUMBER NOT NULL,
	EMAIL VARCHAR2(64),
	MOBILE_PHONE VARCHAR2(10),
	PASSWORD VARCHAR2(64),
	FIRST_NAME VARCHAR2(64),
	LAST_NAME VARCHAR2(64),
	
	PRIMARY KEY( USER_ID )
);

create table CREDIT_CARD (
	CARD_NUMBER VARCHAR2(16) NOT NULL,
	EXPIRE_YEAR VARCHAR2(4) NOT NULL,
	EXPIRE_MONTH VARCHAR2(2) NOT NULL,
	USER_ID NUMBER,
	
	PRIMARY KEY (CARD_NUMBER)
);

create table ADDRESS (
	ADDRESS_ID NUMBER NOT NULL,
	LINE_1 VARCHAR2(64),
	LINE_2 VARCHAR2(64),
	CITY VARCHAR2(32),
	STATE VARCHAR2(32),
	COUNTRY CHAR(3) NOT NULL,
	
	PRIMARY KEY (ADDRESS_ID)
);

create table COUNTRY (
	ID CHAR(2) NOT NULL,
	PHONE_CODE CHAR(3) NOT NULL,
	ALPHA3_CODE CHAR(3) NOT NULL,
	CURRENCY CHAR(3) NOT NULL,
	
	PRIMARY KEY (ID)
);
